# Numpy array dimensions and shapes

As noted in the last recitation, the concept of "array dimension" means something perhaps slightly different from what we have in mind from vector calculus or standard undergraduate linear algebra courses. For example, note the dimensions of the following arrays

In [1]:
import numpy as np

v=np.ones(10)
print('v=', v, ', has Python array dimension v.ndim=', v.ndim, ' and array shape v.shape=', v.shape, '\n\n')
#transposing an array with dimensions (n,) does nothing to it
print('the transpose of v does nothing to it when it has dimensions like (n,): \n v.T=', v.T)
print('------------------------------------------------------------------------------------------------------ \n')
v2=np.ones((1,10))
print('On the other hand:\n v2=', v2, ', has Python array dimension v2.ndim=', v2.ndim, 
      ' and array shape v2.shape=', v2.shape, '\n\n')
print('This time transposing v2 does the following: \n v2.T=', v2.T)
print('------------------------------------------------------------------------------------------------------ \n')

v= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] , has Python array dimension v.ndim= 1  and array shape v.shape= (10,) 


the transpose of v does nothing to it when it has dimensions like (n,): 
 v.T= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------------------------------------------------------------------------------------------ 

On the other hand:
 v2= [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] , has Python array dimension v2.ndim= 2  and array shape v2.shape= (1, 10) 


This time transposing v2 does the following: 
 v2.T= [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
------------------------------------------------------------------------------------------------------ 



Therefore it is important to understand what dimension of an array means in Python. Note how it encloses vector v above with only one pair of square brackets '\[ \]', while for the numpy array v2, it encloses it in **double** square braces '\[\[  \]\]'. What we consider "a vector", namely, v, is considered by Python to have **shape** in the form (n,) and array dimension v.ndim=1. 

On the other hand, it considers v2 an array of shape (n,1) and v2.ndim=2. *it is important to get used to these minor-looking, but important differences in the way Python assigns things*. 

Note what we consider a matrix in our introductory linear algebra courses, is also considere to have array dimension .ndim=2:

In [2]:
A=np.eye(5)
print('A=', A, '\n')
print('A has array dimension A.ndim=', A.ndim)

A= [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

A has array dimension A.ndim= 2


Nonetheless what matters to make the distinction between v2 and A is that A has different **shape** from that of v2:

In [3]:
print('A.shape=', A.shape, ' while v2.shape=', v2.shape)

A.shape= (5, 5)  while v2.shape= (1, 10)


## Turning a row numpy array (1,n) into a column array (n,1):

Note if we use the following reshape command, it turns v2 into a numpy column array:

In [4]:
v2=np.ones((1,10))
print('Initially v2=', v2, ' with v2.shape=', v2.shape, '\n')
v2=v2.reshape(10,1)
print('After reshaping, v2=\n', v2, '\n')
print('v2 now has properties: v2.shape=', v2.shape, '\n Of course it is still the case that v2.ndim=', v2.ndim)

Initially v2= [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]  with v2.shape= (1, 10) 

After reshaping, v2=
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 

v2 now has properties: v2.shape= (10, 1) 
 Of course it is still the case that v2.ndim= 2


**Observation:** *The previous reshaping method required knowing the shape of v2, namely, knowing that it had 10 columns in v2.shape=(1,10)*. It will not always be easy to know the shape of an array after manipulations or being modified by functions. 

One could ask for v2.shape to extract v2's (# rows, #columns) parameters. Another way is to just reshape v2 from a row array to a column array using the "strange syntax" reshape(-1,1) as follows:

In [5]:
v2=np.ones((1,10))
print('Initially v2=', v2, '\n')
v2=v2.reshape(-1,1) #<---this reshaping has the advantage that you do not require to know the shape of v2
print('Now v2=\n', v2)

Initially v2= [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

Now v2=
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


 # What about numpy arrays with shape (n, )?
 
Using the reshape method, you can upgrade a vector type array v of v.ndim=1 and v.shape=(n,) to act like a row or column vector v' with new parameters v'.ndim=2, v'.shape=(1,n) or v'.shape=(n,1), respectively. 

*NOTES:
1. WE SHOW the reshape(1,-1) makes a row vector, and reshape(-1,1) makes a column vector. 
2. Just typing v.reshape(-1,1) does not reshape v. It creates something like a copy of v and reshapes that copy, but does not modify v. You must type v=v.reshape(-1,1)

In [6]:
v=np.ones(10)

print('v=', v, ' initially has Python array dimension v.ndim=', v.ndim, ' and array shape v.shape=', v.shape, '\n\n')
#transposing an array with dimensions (n,) does nothing to it
print('the transpose of v does nothing to it when it has dimensions like (n,): \n v.T=', v.T)
print('------------------------------------------------------------------------------------------------------ \n')

v=v.reshape(1,-1) #<---turns v into row type numpy array
print('v=', v, 'now has has v.ndim=', v.ndim, 'and array shape v.shape=', v.shape, '\n\n')
#transposing an array with dimensions (n,) does nothing to it
print('the transpose of v now does the following:\n v.T=\n', v.T)
print('------------------------------------------------------------------------------------------------------ \n')


v= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]  initially has Python array dimension v.ndim= 1  and array shape v.shape= (10,) 


the transpose of v does nothing to it when it has dimensions like (n,): 
 v.T= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------------------------------------------------------------------------------------------ 

v= [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] now has has v.ndim= 2 and array shape v.shape= (1, 10) 


the transpose of v now does the following:
 v.T=
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
------------------------------------------------------------------------------------------------------ 



In [7]:
v=np.ones(10)
print('v=', v, 'originally has v.ndim=', v.ndim, 'and v.shape=', v.shape, '\n')
v=v.reshape(-1,1) #<---now a column array
print('v=', v, 'now has has v.ndim=', v.ndim, 'and array shape v.shape=', v.shape, '\n\n')
#transposing an array with dimensions (n,) does nothing to it
print('the transpose of v now does the following:\n v.T=\n', v.T)
print('------------------------------------------------------------------------------------------------------ \n')


v= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] originally has v.ndim= 1 and v.shape= (10,) 

v= [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] now has has v.ndim= 2 and array shape v.shape= (10, 1) 


the transpose of v now does the following:
 v.T=
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
------------------------------------------------------------------------------------------------------ 



 Another quick method, which you might see in other codes, is to use the argument np.newaxis parameter. It adds a new dimension to an array. We illustrate the difference between v\[np.newaxis, :\] and v\[:,np.newaxis\] as follows

In [8]:
v=np.ones(10)
print('v=', v, 'originally has v.ndim=', v.ndim, 'and v.shape=', v.shape, '\n')
v=v[np.newaxis, :] #<---turns v into a row array this time, with higher dimension
print('v=', v, 'now has has v.ndim=', v.ndim, 'and array shape v.shape=', v.shape, '\n\n')
 

v= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] originally has v.ndim= 1 and v.shape= (10,) 

v= [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] now has has v.ndim= 2 and array shape v.shape= (1, 10) 




In [9]:
v=np.ones(10)
print('v=', v, '\n')
v=v[:, np.newaxis] #<---turns v into a column array this time
print('v=', v, 'now has has v.ndim=', v.ndim, 'and array shape v.shape=', v.shape, '\n\n')

v= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

v= [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] now has has v.ndim= 2 and array shape v.shape= (10, 1) 




# Multiplying arrays with np.dot(A,B) or np.matmul(A,B):
(Do not reshape, unless abolutely necessary!)

As mentioned in class last time, Python can take the inner products of two arrays v1 and v2 of vi.ndim=1 with vi.shape=(n,) **without having to reshape them!**. We illustrate this with a matrix, we extract rows and columns of it and we note that we do not have to reshape anything since **by default, numpy takes rows and columns of arrays as being 1-dimensional numpy arrays with shapes of type (n,)!**



In [10]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print('A.shape=', A.shape, '\n')

v1=A[0,:]
print('v1=', v1, 'with v1.shape=', v1.shape)
w1=A[:,0]
print('w1=', w1, 'with w1.shape=', w1.shape)

A.shape= (3, 3) 

v1= [1 2 3] with v1.shape= (3,)
w1= [1 4 7] with w1.shape= (3,)


Note in the above cell that it treats v1 and w1 as having the same shape! Even though v1 was extracted from the first row of A and w1 from the first **column** of A! That is why np.dot(v1,w1) or np.matmul(v1,w1) both work and essentially take the inner product both:

In [11]:
print('np.dot(v1,w1)=', np.dot(v1,w1))
print('np.matmul(v1,w1)=', np.matmul(v1,w1))

np.dot(v1,w1)= 30
np.matmul(v1,w1)= 30


So, under what numpy calls a 1 dimensional array, if v1 and w1 have the same shape, it treats their product as an inner product! **But only because they are one-dimensional numpy arrays.**

Trouble breaks loose if I had tried to reshape to the same shape when they are **first upgraded to two-dimensional arrays with the same shape!** In other words, note what happens and we get ERROR MESSAGE:

In [12]:
#THIS GIVES ERROR MESSAGE!

v1=v1.reshape(-1,1)
w1=w1.reshape(-1,1)
np.dot(v1,w1) #<---same with np.matmul()

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

This is because now, for what Python denotes as 2-dimensional numpy arrays, we call these in linear algebra matrices. And matrices need to have: for AB to be defined, we require #(columns A)=#(rows B). Thus the following now works:

In [13]:
v1=v1.reshape(-1,1)
w1=w1.reshape(1,-1)
print('np.dot(v1,w1)= outer product of v1 and w1= \n', np.dot(v1,w1)) #<--outer product!
print('\n')
print('np.dot(w1,v1)= inner product of w1 and v1=\n', np.dot(w1,v1))#<---inner product! 

np.dot(v1,w1)= outer product of v1 and w1= 
 [[ 1  4  7]
 [ 2  8 14]
 [ 3 12 21]]


np.dot(w1,v1)= inner product of w1 and v1=
 [[30]]


# Why these Python conventions are of interest to us:

These conventions are important to understand from the array manipulation standpoint because, for example, if I give you two arrays A, B and we want to do the outer product of a certain COLUMN of A with a certain ROW of B, we cannot just extract them so easily and use np.dot(COL,ROW), as the following shows:

In [14]:
A=A=np.array([
    [1,2],
    [4,5],
    [7,8]
])

B=np.array([[1,0,-1],  [0, 2, 0]])
print('A=\n', A, '\n')
print('B=\n', B, '\n')

print('column 0 of A is A[:,0]=', A[:,0], 'and row 1 of B is B[1,:]=', B[1,:])
print('Thus np.dot(A[:,0], B[1,:])=', np.dot(A[:,0], B[1,:]), '<---NOT OUTER PRODUCT!')

A=
 [[1 2]
 [4 5]
 [7 8]] 

B=
 [[ 1  0 -1]
 [ 0  2  0]] 

column 0 of A is A[:,0]= [1 4 7] and row 1 of B is B[1,:]= [0 2 0]
Thus np.dot(A[:,0], B[1,:])= 8 <---NOT OUTER PRODUCT!


This is because, as mentioned above, **both rows and columns of a 2-dimensional numpy array are seen by Python as a 1-dimensional numpy array!** Thus it does not see them as having shapes like (3,1) and (1,3) respectively and does not compute an outer product!

This is why reshape is useful. So we upgrade the columns and rows of interest to 2-dimensional arrays and now use np.dot():

In [15]:
column_of_A= A[:,0].reshape(-1,1)
row_of_B=B[1,:].reshape(1,-1)
print('Now we can do the outer product and get:\n')
print(' with column 0 of A:\n\n',  column_of_A, '\n and row 1 of B: ', row_of_B, '\n\n')
print(' we now have the outer product= np.dot(column_of_A, row_of_B)=\n', np.dot(column_of_A, row_of_B))
 

Now we can do the outer product and get:

 with column 0 of A:

 [[1]
 [4]
 [7]] 
 and row 1 of B:  [[0 2 0]] 


 we now have the outer product= np.dot(column_of_A, row_of_B)=
 [[ 0  2  0]
 [ 0  8  0]
 [ 0 14  0]]


# Nonetheless:

Even though Python sees stuff like np.array([0,0,1]) as a 1-dimensional numpy array, it still knows how to redefine a column of a 2-dimensional numpy array if necessary, or a row if necessary. It depends on using the correct row and column syntax wihin the 2-dimensional array:

Suppose we want to change column A[:,1] by [0,0,1]^T, and then row 1 of A by [-3,-3]: 

In [16]:
A=A=np.array([
    [1,2],
    [4,5],
    [7,8]
])
print('Initially, A=\n', A, '\n\n')
A[:,1]=np.array([0,0,1])
print('Now A=\n', A, '\n\n')

A[1,:]=np.array([-3,-3])
print('Now A=\n', A, '\n\n')

Initially, A=
 [[1 2]
 [4 5]
 [7 8]] 


Now A=
 [[1 0]
 [4 0]
 [7 1]] 


Now A=
 [[ 1  0]
 [-3 -3]
 [ 7  1]] 




 # Other manipulations, swapping rows and columns of an array
 
 Suppose we want to swap the first row of A with the last row of A. Note the interesting-looking way Python can do this, using the following syntax:

In [17]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print('A=', A, '\n')

A[[0,2],:]=A[[2,0],:] # for ROWS can also do A[[0,2]]=A[[2,0]]. 
print('Now \n A=', A)

A= [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Now 
 A= [[7 8 9]
 [4 5 6]
 [1 2 3]]


For columns it is similar:

In [18]:
A[:,[0,2]]=A[:,[2,0]] # for columns it always is A[:,[0,2]]=A[:,[2,0]] 
print('After swapping colums 0 and 2, now A=\n', A)

After swapping colums 0 and 2, now A=
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
